# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
    assignees:
       - "RonHouben"
       
  - package-ecosystem: "npm"
    directory: "/packages/audio-engine"
    schedule:
      interval: "weekly"
    assignees:
       - "RonHouben"
       
  - package-ecosystem: "npm"
    directory: "/packages/audio-engine-react"
    schedule:
      interval: "weekly"
    assignees:
       - "RonHouben"
       
  - package-ecosystem: "npm"
    directory: "/packages/database"
    schedule:
      interval: "weekly"
    assignees:
       - "RonHouben"
       
  - package-ecosystem: "npm"
    directory: "/packages/eslint-config-custom"
    schedule:
      interval: "weekly"
    assignees:
       - "RonHouben"
       
  - package-ecosystem: "npm"
    directory: "/packages/exercise-engine"
    schedule:
      interval: "weekly"
    assignees:
       - "RonHouben"
       
  - package-ecosystem: "npm"
    directory: "/packages/music-notes"
    schedule:
      interval: "weekly"
    assignees:
       - "RonHouben"
   
  - package-ecosystem: "npm"
    directory: "/packages/ui"
    schedule:
      interval: "weekly"
    assignees:
       - "RonHouben"
